name: linux

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - cvmfs_base: 'sw-nightlies.hsf.org'
          ENVIRONMENT: 'key4hep'
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: key4hep/key4hep-actions/downstream-build@main
